FROM srikarst/maven-3.9.6-java-21:1.0.3
 
USER 0
 
RUN mkdir -p /usr/root/whatsapp-socket-handler
WORKDIR /usr/root/whatsapp-socket-handler

RUN apt-get update && apt install libssl-dev -y

RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb && dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb 